Import Libraries

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD

Generate dummy data

In [ ]:
import numpy as np
x_train = np.random.random((1000,20))
y_train = keras.utils.to_categorical(np.random.randint(10, size = (1000,1)), num_classes=10)
x_test = np.random.random((100, 20))
y_test = keras.utils.to_categorical(np.random.randint(10, size = (100,1)), num_classes=10)

Analyze data

In [ ]:
x_train[50:51]

array([[0.8208278 , 0.78317295, 0.34976688, 0.99810861, 0.20777506,
        0.38151681, 0.35841154, 0.9302519 , 0.70916307, 0.64000364,
        0.35637404, 0.82641813, 0.77894717, 0.87929618, 0.91880171,
        0.55820852, 0.56604605, 0.3879041 , 0.93071035, 0.15874266]])

In [ ]:
y_train[50:51]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
x_test[0]

array([0.71206785, 0.65937866, 0.31049094, 0.25591267, 0.89819303,
       0.03028801, 0.56837098, 0.75237497, 0.36723571, 0.66999319,
       0.16096631, 0.0044051 , 0.53785767, 0.51990422, 0.56116588,
       0.36041236, 0.16116737, 0.22050449, 0.81405777, 0.94916783])

In [ ]:
y_test[0]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.], dtype=float32)

Create the model

In [ ]:
model = Sequential()
model.add(Dense(64, activation='relu', input_dim=20))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

Compile the model

In [ ]:
model.compile(loss='categorical_crossentropy', 
              optimizer = sgd,
              metrics = ['accuracy'])

In [ ]:
model.fit(x_train, y_train,
          epochs = 1000,
          batch_size = 128)

Epoch 1/1000
8/8 [==============================] - 1s 3ms/step - loss: 2.4028 - accuracy: 0.0910
Epoch 2/1000
8/8 [==============================] - 0s 3ms/step - loss: 2.3474 - accuracy: 0.1020
Epoch 3/1000
8/8 [==============================] - 0s 3ms/step - loss: 2.3347 - accuracy: 0.1170
Epoch 4/1000
8/8 [==============================] - 0s 3ms/step - loss: 2.3361 - accuracy: 0.1090
Epoch 5/1000
8/8 [==============================] - 0s 3ms/step - loss: 2.3116 - accuracy: 0.1080
Epoch 6/1000
8/8 [==============================] - 0s 3ms/step - loss: 2.3124 - accuracy: 0.1000
Epoch 7/1000
8/8 [==============================] - 0s 4ms/step - loss: 2.3185 - accuracy: 0.0940
Epoch 8/1000
8/8 [==============================] - 0s 3ms/step - loss: 2.3175 - accuracy: 0.0930
Epoch 9/1000
8/8 [==============================] - 0s 3ms/step - loss: 2.3043 - accuracy: 0.1100
Epoch 10/1000
8/8 [==============================] - 0s 3ms/step - loss: 2.3057 - accuracy: 0.0980
Epoch 11/1000
8/8 [

In [ ]:
score = model.evaluate(x_test, y_test, batch_size=128,)

1/1 [==============================] - 0s 205ms/step - loss: 2.8213 - accuracy: 0.0700


In [ ]:
model.metrics_names

['loss', 'accuracy']

In [ ]:
score

[2.8213231563568115, 0.07000000029802322]

Model prediction

In [ ]:
model.predict(x_train[0:1], batch_size=None, verbose=0, steps=None)

array([[0.15713462, 0.10004174, 0.16969709, 0.04981998, 0.08786649,
        0.1357368 , 0.18470927, 0.03209208, 0.04159304, 0.04130889]],
      dtype=float32)

In [ ]:
y_train[0:1]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)